﻿-- TẠO CSDL
CREATE DATABASE QLBH
GO
-- TẠO BẢNG
CREATE TABLE KHACH_HANG (
    MaKH CHAR(6), 
    HoTenKH NVARCHAR(100) NOT NULL, 
    MatKhau VARCHAR(255) NOT NULL, 
    SDT VARCHAR(15) NOT NULL, 
    Email VARCHAR(100) NOT  NULL,
    DiaChi NVARCHAR(255) NOT NULL, 
    PRIMARY KEY (MaKH)
);

CREATE TABLE SAN_PHAM (
    MaSP CHAR(6), 
    TenSP NVARCHAR(100) NOT NULL, 
    MoTaSP NTEXT, 
    GiaNiemYet DECIMAL(10,0) NOT NULL, 
	SoLuongTon INT NOT NULL DEFAULT(0) CHECK (SoLuongTon >= 0),
    NgayTaoSP DATE NOT NULL, 
    NgayXoaSP DATE, 
    MaDM CHAR(6) NOT NULL, 
    MaNCC CHAR(6) NOT NULL, 
    PRIMARY KEY (MaSP)
);

CREATE TABLE DANH_MUC_SP (
    MaDM CHAR(6), 
    TenDM NVARCHAR(50) NOT NULL, 
    MoTaDM NTEXT, 
    TrangThaiDM BIT NOT NULL, 
    NgayTaoDM DATE NOT NULL, 
    NgayXoaDM DATE, 
    PRIMARY KEY (MaDM)
);

CREATE TABLE GIO_HANG (
    MaGioHang CHAR(6), 
    NgayTaoGH DATE NOT NULL, 
    NgayCapNhatGH DATE, 
    MaKH CHAR(6), 
    PRIMARY KEY (MaGioHang)
);

CREATE TABLE CHI_TIET_GIO_HANG (
    MaGioHang CHAR(6), 
    MaSP CHAR(6), 
    SoLuong INT NOT NULL CHECK (SoLuong > 0), 
    PRIMARY KEY (MaGioHang, MaSP)
);

CREATE TABLE DON_HANG (
    MaDH CHAR(6), 
    NgayDatDon DATE NOT NULL, 
    MaKH CHAR(6) NOT NULL,  
    PRIMARY KEY (MaDH)
);

CREATE TABLE CHI_TIET_DON_HANG (
    MaDH CHAR(6), 
    MaSP CHAR(6), 
    SoLuong INT NOT NULL CHECK (SoLuong > 0), 
    DonGia DECIMAL(10,0) NOT NULL, 
    PRIMARY KEY (MaDH, MaSP)
);

CREATE TABLE DON_VI_VAN_CHUYEN (
    MaDVVC CHAR(6), 
    TenDVVC NVARCHAR(100)  NOT NULL, 
    SDT VARCHAR(15)  NOT NULL, 
    Email VARCHAR(100), 
    DiaChi NVARCHAR(255), 
    PRIMARY KEY (MaDVVC)
);

CREATE TABLE THONG_TIN_GIAO_HANG (
    MaVanDon CHAR(6), 
    NgayTiepNhan DATE, 
    PhiGiao DECIMAL(10,0) NOT NULL CHECK (PhiGiao > 0), 
    NgayGiao DATE, 
    TrangThaiGiao NVARCHAR(20) CHECK (TrangThaiGiao IN (N'Chờ giao hàng', N'Đang giao hàng', N'Giao hàng thành công', N'Chờ hoàn hàng', N'Đang hoàn hàng', N'Đã hoàn hàng')),
    MaDH CHAR(6) NOT NULL, 
    MaDVVC CHAR(6) NOT NULL, 
    PRIMARY KEY (MaVanDon)
);

CREATE TABLE DANH_GIA_SP (
    MaDanhGia CHAR(6), 
    DiemDanhGia INT NOT NULL CHECK (DiemDanhGia BETWEEN 1 AND 5)  , 
    NoiDungDanhGia NVARCHAR(255), 
    NgayDanhGia DATE, 
    MaKH CHAR(6) NOT NULL, 
    MaSP CHAR(6) NOT NULL,
	MaDH CHAR(6) NOT NULL,
    PRIMARY KEY (MaDanhGia)
);

CREATE TABLE NHAN_VIEN (
    MaNV CHAR(6), 
    HoTenNV NVARCHAR(100) NOT NULL, 
    GioiTinh NVARCHAR(3) CHECK (GioiTinh IN (N'Nam', N'Nữ')) NOT NULL, 
    SDT VARCHAR(15) NOT NULL, 
    DiaChi NVARCHAR(255), 
    Email VARCHAR(100), 
    VaiTro NVARCHAR(50) CHECK (VaiTro IN (N'Kế Toán', N'Kho', N'Chăm sóc khách hàng', N'Đóng hàng', N'Quản lý')),
    PRIMARY KEY (MaNV)
);

CREATE TABLE NHA_CUNG_CAP (
    MaNCC CHAR(6), 
    TenNCC NVARCHAR(100) NOT NULL, 
    DiaChi NVARCHAR(255), 
    SDT VARCHAR(15) NOT NULL,
    Email VARCHAR(100), 
    PRIMARY KEY (MaNCC)
);

CREATE TABLE PHIEU_DAT_HANG (
    MaPhieuDatHang CHAR(6), 
    NgayDat DATE NOT NULL, 
    MaNVLap CHAR(6) NOT NULL, 
    MaNCC CHAR(6) NOT NULL, 
    PRIMARY KEY (MaPhieuDatHang)
);

CREATE TABLE CHI_TIET_DAT_HANG (
    MaPhieuDatHang CHAR(6), 
    MaSP CHAR(6), 
    SoLuongDat INT NOT NULL CHECK (SoLuongDat > 0), 
    DonGiaNhap DECIMAL(10,0) NOT NULL CHECK (DonGiaNhap > 0), 
    PRIMARY KEY (MaPhieuDatHang, MaSP)
);

CREATE TABLE PHIEU_NHAP_HANG (
    MaPhieuNhap CHAR(6), 
    NgayNhap DATE NOT NULL, 
    MaNVLap CHAR(6) NOT NULL, 
    MaPhieuDatHang CHAR(6) NOT NULL, 
    MaNCC CHAR(6), 
    PRIMARY KEY (MaPhieuNhap)
);

CREATE TABLE CHI_TIET_NHAP_HANG (
    MaPhieuNhap CHAR(6), 
    MaSP CHAR(6), 
    SoLuongNhap INT NOT NULL CHECK (SoLuongNhap > 0), 
    PRIMARY KEY (MaPhieuNhap, MaSP)
);


-- TẠO KHÓA NGOẠI
ALTER TABLE SAN_PHAM ADD CONSTRAINT FK_SP_DM FOREIGN KEY (MaDM) REFERENCES DANH_MUC_SP(MaDM);
ALTER TABLE SAN_PHAM ADD CONSTRAINT FK_SP_NCC FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC);

ALTER TABLE GIO_HANG ADD CONSTRAINT FK_GIO_HANG_KH FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH);

ALTER TABLE CHI_TIET_GIO_HANG ADD CONSTRAINT FK_CTGIOHANG_GH FOREIGN KEY (MaGioHang) REFERENCES GIO_HANG(MaGioHang);
ALTER TABLE CHI_TIET_GIO_HANG ADD CONSTRAINT FK_CTGIOHANG_SP FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP);

ALTER TABLE DON_HANG ADD CONSTRAINT FK_DONHANG_KH FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH);

ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CTDONHANG_DH FOREIGN KEY (MaDH) REFERENCES DON_HANG(MaDH);
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CTDONHANG_SP FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP);

ALTER TABLE THONG_TIN_GIAO_HANG ADD CONSTRAINT FK_TTGH_DH FOREIGN KEY (MaDH) REFERENCES DON_HANG(MaDH);
ALTER TABLE THONG_TIN_GIAO_HANG ADD CONSTRAINT FK_TTGH_DVVC FOREIGN KEY (MaDVVC) REFERENCES DON_VI_VAN_CHUYEN(MaDVVC);

ALTER TABLE DANH_GIA_SP ADD CONSTRAINT FK_DANHGIA_KH FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH);
ALTER TABLE DANH_GIA_SP ADD CONSTRAINT FK_DANHGIA_SP FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP);
ALTER TABLE DANH_GIA_SP ADD CONSTRAINT FK_DANHGIA_DH FOREIGN KEY (MaDH) REFERENCES DON_HANG(MaDH);
ALTER TABLE DANH_GIA_SP ADD CONSTRAINT FK_DANHGIA_CHITIETDH FOREIGN KEY (MaDH, MaSP) REFERENCES CHI_TIET_DON_HANG (MaDH, MaSP);

ALTER TABLE PHIEU_DAT_HANG ADD CONSTRAINT FK_PDH_NV FOREIGN KEY (MaNVLap) REFERENCES NHAN_VIEN(MaNV);
ALTER TABLE PHIEU_DAT_HANG ADD CONSTRAINT FK_PDH_NCC FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC);

ALTER TABLE CHI_TIET_DAT_HANG ADD CONSTRAINT FK_CTDPH_PDH FOREIGN KEY (MaPhieuDatHang) REFERENCES PHIEU_DAT_HANG(MaPhieuDatHang);
ALTER TABLE CHI_TIET_DAT_HANG ADD CONSTRAINT FK_CTDPH_SP FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP);

ALTER TABLE PHIEU_NHAP_HANG ADD CONSTRAINT FK_PNH_NV FOREIGN KEY (MaNVLap) REFERENCES NHAN_VIEN(MaNV);
ALTER TABLE PHIEU_NHAP_HANG ADD CONSTRAINT FK_PNH_PDH FOREIGN KEY (MaPhieuDatHang) REFERENCES PHIEU_DAT_HANG(MaPhieuDatHang);
ALTER TABLE PHIEU_NHAP_HANG ADD CONSTRAINT FK_PNH_NCC FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC);

ALTER TABLE CHI_TIET_NHAP_HANG ADD CONSTRAINT FK_CTNH_PNH FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEU_NHAP_HANG(MaPhieuNhap);
ALTER TABLE CHI_TIET_NHAP_HANG ADD CONSTRAINT FK_CTNH_SP FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP);
